from datetime import date, timedelta
from random import randint
from ..models.book import Book
from ..models.customer import Customer
from ..models.loan import Loan


books = [
    Book(
        title="The Witty Rascals",
        author="Hideki Saito",
        description='"The Witty Rascals" is a delightful tale about a group of mischievous friends who go on an adventure in search of hidden treasure. The story takes place in a small village nestled in the rolling hills of the countryside.',
    ),
    Book(
        title="The Skilled Dogs",
        author="Elizabeth Malone",
        description='"The Skilled Dogs" is an exciting adventure story set in a world where dogs have developed unique talents and abilities beyond what we commonly associate with them. In this world, dogs are not just pets but valued members of society, serving in a wide range of important roles.',
    ),
    Book(
        title="The Talkative Legends",
        author="Carlo Doherty",
        description='"The Talkative Legends" is a captivating book that brings together the stories and wisdom of some of the greatest talkers of all time. From ancient philosophers and poets to modern-day intellectuals and activists, this book explores the lives and works of those who have left an indelible mark on the world through their words.',
    ),
    Book(
        title="The Comedic Hippos",
        author="Jemmie Edmonds",
        description='"The Comedic Hippos" is a heartwarming tale about a group of hippos who dream of becoming comedians. Set in the lush, tropical landscape of the African savannah, the story follows the adventures of four unlikely friends who set out to make their mark in the world of comedy.',
    ),
    Book(
        title="The Desperate Skaters",
        author="Rose Hallahan",
        description='"The Desperate Skaters" is a thrilling story about a group of young skaters who find themselves caught up in a dangerous world of crime and deception. Set in the gritty and urban landscape of a big city, the story follows the adventures of four friends who love nothing more than skating together.',
    ),
    Book(
        title="The Amazing Godfathers",
        author="Matthew Peterson",
        description='"The Amazing Godfathers" is an epic tale of power, loyalty, and family in a world of organized crime. Set in the dark and dangerous underworld of a bustling city, the story follows the rise and fall of a powerful mafia family known as the Godfathers.',
    ),
    Book(
        title="The Obtuse Puppies",
        author="Mariele Pegram",
        description='"The Obtuse Puppies" is a humorous tale about a litter of puppies who just can\'t seem to get anything right. Set in the idyllic countryside, the story follows the adventures of four lovable but clumsy puppies named Bella, Charlie, Daisy, and Eddie.',
    ),
    Book(
        title="The Withering Herbs",
        author="Jamba Adeoye",
        description='"The Withering Herbs" is a suspenseful story that delves into the dangerous world of herbal medicine and the high stakes of the pharmaceutical industry. Set in the lush and beautiful countryside, the story follows the journey of a young herbalist who is tasked with uncovering the truth behind a mysterious illness that is sweeping through her village.',
    ),
    Book(
        title="The Smug Mammals",
        author="Isaiah Madron",
        description='"The Smug Mammals" is a satirical tale that takes a humorous look at the world of animal behavior and social dynamics. Set in the sprawling savannahs of Africa, the story follows a group of anthropomorphic mammals who are all vying for power and influence in their community.',
    ),
    Book(
        title="The Aggressive Crickets",
        author="Isaiah Madron",
        description='"The Aggressive Crickets" is an action-packed tale that takes place in the lush green fields and meadows of the countryside. The story follows a group of crickets who are forced to band together to protect their community from a looming threat.',
    ),
    Book(
        title="The Unsubtle Flamingos",
        author="Layla Snowding",
        description='"The Unsubtle Flamingos" is an irreverent story that takes a lighthearted look at the world of high society and glamour. Set against the backdrop of a luxurious tropical resort, the story follows a flock of flamboyant flamingos as they navigate the ups and downs of life in the spotlight.',
    ),
    Book(
        title="The Proper Warriors",
        author="Dean Blumson",
        description='"The Proper Warriors" is an action-packed adventure that transports readers to a fantastical world of sword and sorcery. The story follows a group of skilled warriors who must band together to defend their land against a powerful and malevolent sorcerer.',
    ),
    Book(
        title="The Booming Mushrooms",
        author="Daryle Bhatia",
        description='"The Booming Mushrooms" is an imaginative story that takes readers on a journey of discovery through a mystical forest. The story follows a young girl who stumbles upon a secret world hidden deep within the forest.',
    ),
    Book(
        title="The Rude Pots",
        author="Nile Giles",
        description='"The Rude Pots" is an irreverent story that follows a group of mischievous kitchen pots who get into all sorts of trouble in a bustling restaurant. The pots, each with their unique personality and quirks, are tired of being used and abused by the restaurant staff and decide to take matters into their own hands.',
    ),
    Book(
        title="The Dancing Fishes",
        author="Angelle Joyce",
        description='"The Dancing Fishes" is a delightful tale that brings to life a vibrant underwater world. The story follows a school of fish who love to dance and perform, led by their fearless leader, a plucky and determined fish named Daphne.',
    ),
    Book(
        title="The Fussy Giraffes",
        author="Roksana Kaczmarek",
        description='"The Fussy Giraffes" is a lighthearted tale that centers around a group of giraffes who are known for being especially picky eaters. The story follows the giraffes as they journey through the savannah in search of the perfect meal, each one searching for their own unique delicacy.',
    ),
    Book(
        title="The Smooth Horses",
        author="Corine Fay",
        description='"The Smooth Horses" is an exhilarating tale that follows a group of horses with an exceptional talent for speed and agility. The story centers around two best friends, Blaze and Thunder, who dream of becoming champions in the annual horse racing competition.',
    ),
    Book(
        title="The Backwards Parrots",
        author="Aishwarya Mukherjee",
        description='"The Backwards Parrots" is a whimsical tale that centers around a group of parrots who have an unusual habit of speaking backwards. The story follows the adventures of Polly, the newest member of the flock, as she learns to communicate in this unique and quirky way.',
    ),
    Book(
        title="The Nefarious Soup",
        author="Lottie Hargrave",
        description='"The Nefarious Soup" is a suspenseful tale that centers around a small town and the strange soup that begins to affect the behavior of its residents. The story follows a young chef as she uncovers the dark secrets behind the soup\'s unusual properties and works to save her community from its dangerous effects.',
    ),
    Book(
        title="The Boring Ponies",
        author="Sid Murtagh",
        description='"The Boring Ponies" is a charming tale that follows a group of ponies living in a sleepy little village. The story centers around the daily lives of these unremarkable ponies as they go about their mundane routines, often struggling to find excitement or purpose in their simple existence.',
    ),
    Book(
        title="The Innocent Elephants",
        author="Kearney Weippert",
        description='"The Innocent Elephants" is a poignant story that follows a herd of elephants living in the African savannah. The story centers around the youngest member of the herd, a curious and spirited calf named Jumbo, as he discovers the world around him and learns important lessons about life and survival.',
    ),
    Book(
        title="The Fishy Ants",
        author="Carly Lei",
        description='"The Fishy Ants" is an uplifting story that follows a colony of ants who live near a river. Unlike most ants, who spend their days scurrying about on the ground, these ants are drawn to the water and spend much of their time swimming and playing in the river.',
    ),
    Book(
        title="The Moody Underdogs",
        author="Nile Awate",
        description='"The Moody Underdogs" is a heartwarming story about a group of dogs who live in a shelter. Each of the dogs has their own unique personality and quirks, and they all have one thing in common: they haven\'t been adopted yet.',
    ),
    Book(
        title="The Offensive Muffins",
        author="Adena Aitchinson",
        description='"The Offensive Muffins" is a witty story about a group of muffins who live in a small bakery. Trouble arises when a new muffin, named Blueberry, joins the group. Blueberry is rude and obnoxious, insulting the other muffins and causing chaos in the bakery.',
    ),
    Book(
        title="The Awkward Submarines",
        author="Haze Vanyukov",
        description='"The Awkward Submarines" is an amusing tale about a group of submarines that are not quite like the others. They are all a bit awkward, clumsy and unsure of themselves, which makes them the laughing stock of the underwater world.',
    ),
    Book(
        title="The Nasty Fossils",
        author="Rosita Ortiz",
        description='"The Nasty Fossils" is a thrilling adventure novel that takes readers on a journey through time. The story begins with a team of paleontologists on a dig site, searching for fossils from millions of years ago. As they work, they uncover something unexpected and terrifying: a fossilized creature that should not exist.',
    ),
    Book(
        title="The Wavy Rabbits",
        author="Astor Blau",
        description='"The Wavy Rabbits" is a heartwarming tale about a group of rabbits who embark on an epic adventure together. The story follows a young rabbit named Daisy who dreams of leaving her quiet life behind and exploring the world beyond her warren.',
    ),
    Book(
        title="The Suave Rangers",
        author="Alvinia Whannel",
        description='"The Suave Rangers" is an action-packed adventure that follows a team of elite agents on a mission to save the world from a dangerous criminal organization. Along the way, the team faces a series of dangerous obstacles, from high-speed car chases to brutal hand-to-hand combat.',
    ),
    Book(
        title="The Grumpy Hedges",
        author="Ravi Parsa",
        description='"The Grumpy Hedges" is a humorous story about a group of hedges that always seem to be in a bad mood. The story is set in a small garden in a quaint English village. Despite being beautiful and well-maintained, the hedges have a reputation for being grumpy and unpleasant to anyone who tries to interact with them.',
    ),
    Book(
        title="The Sulking Posers",
        author="Rosalina Lozada",
        description='"The Sulking Posers" is an imaginative book that takes readers on a journey through the world of modeling and fashion. The story revolves around a group of models who are known for their incredible beauty and poise on the runway, but who are also notorious for their bad attitudes and diva behavior behind the scenes.',
    ),
    Book(
        title="The Pouting Stickers",
        author="Elfreda Burt",
        description='"The Pouting Stickers" is a quirky children\'s book that brings stickers to life in a whole new way. The story follows a group of stickers who have been stuck on a sheet in a toy store for far too long, and who are feeling neglected and unappreciated.',
    ),
    Book(
        title="The Stormy Riders",
        author="Loretta McDowell",
        description='"The Stormy Riders" is a fast-paced novel that follows a group of courageous cowboys who ride across the Wild West in search of justice. Led by the fearless and sharpshooting protagonist, Jack "The Storm" Johnson, this group of outlaws-turned-heroes stops at nothing to protect the innocent and bring criminals to justice.',
    ),
    Book(
        title="The Overpowered Bikers",
        author="Sam Owolabi",
        description='"The Overpowered Bikers" is a thrilling novel that takes place in a world where motorcycle racing is the most popular sport. The story follows a group of highly skilled and ambitious bikers who are determined to become the best in the world. However, their dreams are threatened by a powerful and corrupt organization that controls the sport and will stop at nothing to maintain their dominance.',
    ),
    Book(
        title="The Skulking Bagpipes",
        author="Wylie Jarrelt",
        description='"The Skulking Bagpipes" is a tale of mystery and intrigue, set in the Scottish highlands. When a bagpiper is found murdered on the grounds of a remote castle, the local police are at a loss for clues. But when a mysterious stranger arrives in town and begins asking questions, they start to suspect that there is more to this case than meets the eye.',
    ),
    Book(
        title="The Iconic Computers",
        author="Magdalena Jakubovics",
        description='"The Iconic Computers" is a fascinating book that takes the reader on a journey through the history of computing. From the earliest computers to the introduction of the personal computer to the development of the internet and the rise of smartphones, "The Iconic Computers" covers all the major milestones in computing history.',
    ),
    Book(
        title="The Discombobulated Gems",
        author="Bobby Vize",
        description='"The Discombobulated Gems" is an adventure novel that follows the story of three friends who embark on a treasure hunt to find a legendary gem that is said to have the power to grant any wish. Fragments of the gem are scattered in different locations around the world, and the friends must decipher cryptic clues and overcome dangerous obstacles to find them.',
    ),
    Book(
        title="The Extra Hats",
        author="Vimal Sundaram",
        description='"The Extra Hats" is an imaginative tale about a town where everyone wears hats. The protagonist discovers that she has a special talent for making hats that are unlike any others in town. With her newfound skill, she begins to create hats that are extraordinary, each one more unique and magical than the last.',
    ),
    Book(
        title="The Squeaky Oxen",
        author="Kyler Luther",
        description="\"The Squeaky Oxen\" is a tale about a group of oxen who just can't seem to stop making noise. Despite their best efforts, they constantly squeak as they go about their daily business on the farm. The other animals find their sounds quite amusing and often make fun of them. However, the oxen are determined to prove that they're more than just their noisy reputations",
    ),
    Book(
        title="The Vague Burglars",
        author="April Scay",
        description='"The Vague Burglars" is a thrilling story that follows a group of seasoned detectives as they attempt to solve a series of seemingly unrelated burglaries that are plaguing a small town. Despite their expertise, the detectives struggle to make progress in their investigation as the burglars leave no discernible evidence behind, and their motives are unclear.',
    ),
    Book(
        title="The Overt Aunties",
        author="Annie Jones",
        description='"The Overt Aunties" is a book that revolves around a group of bold and confident aunties who take on the world with their fearless personalities. These women are not your typical sweet and gentle aunties, but rather, they are strong and assertive in their actions and words.',
    ),
    Book(
        title="The Menacing Bushes",
        author="Devika Thaman",
        description='"The Menacing Bushes" is a book that explores the supernatural and the unknown. The story follows a group of teenagers who decide to explore a remote forest rumored to be haunted by malevolent spirits. As they delve deeper into the woods, they encounter a strange and unsettling presence among the bushes. The air is filled with an eerie silence that seems to speak of danger lurking just out of sight.',
    ),
    Book(
        title="The Powerful Chunks",
        author="Sibyl Durber",
        description='"The Powerful Chunks" is a thrilling novel that follows the journey of a group of friends who stumble upon an ancient artifact that possesses the power to grant incredible strength and abilities to its wielder. However, they soon realize that they are not the only ones seeking this power, and must fight off a dangerous group of villains who will stop at nothing to obtain it.',
    ),
    Book(
        title="The Peculiar Teabags",
        author="Teniola Adeyemi",
        description='"The Peculiar Teabags" is a fantastic tale of a young woman who discovers a magical teapot that can transport her to different worlds through the power of tea. She soon becomes obsessed with collecting different types of tea from around the world, each with their unique properties, and uses them to explore fantastical realms full of strange creatures and challenges.',
    ),
    Book(
        title="The Lush Pieces",
        author="Mitra Ramachandran",
        description='"The Lush Pieces" is an book that tells the story of a struggling artist, Ava, who is trying to find inspiration for her next big project. In her search, she stumbles upon a mysterious antique shop filled with unique and captivating items. There, she discovers a set of intricate wooden puzzles that seem to hold a magical quality, transporting her to different worlds and timelines as she solves them.',
    ),
    Book(
        title="The Unintended Teapots",
        author="Temidayo Joseph",
        description='"The Unintended Teapots" is an interesting book that explores the lives of a group of teapots who find themselves in unexpected situations. The story follows the teapots as they navigate their way through various challenges, from being used for purposes other than holding tea to dealing with unexpected accidents and mishaps.',
    ),
    Book(
        title="The Rich Poets",
        author="Tito Hargrove",
        description='"The Rich Poets" is a satisfying book that delves into the lives of a group of poets who have achieved great success and fame in the literary world. The book explores their struggles, triumphs, and the sacrifices they made to achieve their success.',
    ),
    Book(
        title="The Fragile Otters",
        author="Hamlin Camilletti",
        description='"The Fragile Otters" is a heartwarming tale about a group of otters struggling to survive in a world full of challenges. These creatures, who are known for their playful nature and love for water, are facing a tough time due to the changing climate and human interference in their habitat.',
    ),
    Book(
        title="The Flexible Chipmunks",
        author="Cherilynn Watkins",
        description="\"The Flexible Chipmunks\" is a children's book that tells the story of a group of chipmunks who are determined to pursue their dreams despite their physical limitations. The main character, a chipmunk named Chip, dreams of becoming a dancer but is constantly told that chipmunks aren't graceful enough for the art. However, Chip refuses to give up.",
    ),
    Book(
        title="The Suspicious Sheep",
        author="Maksim Gusev",
        description='"The Suspicious Sheep" is a mystery novel that follows a group of detectives as they try to solve a string of strange crimes that have been happening on a small sheep farm. The farmer is convinced that one of his own sheep is behind the strange occurrences, but the detectives are not so sure.',
    ),
    Book(
        title="The Hungry Swans",
        author="Gwan Min Ki",
        description='"The Hungry Swans" is a peculiar tale about a family of swans that live in a pond in a quiet park. The swans, who are known for their elegance and beauty, have a tendency to be constantly hungry. The story follows the journey of the young swan family as they go through various adventures in search of food to satisfy their endless appetite.',
    ),
]

customers = [
    Customer(
        library_card_number="PD-569797-8874",
        name="Paul Davies",
        email="paul.davies@gmail.com",
    ),
    Customer(
        library_card_number="MJ-600731-1698",
        name="Mark Jackson",
        email="mark.jackson@live.com",
    ),
    Customer(
        library_card_number="TF-781410-1836",
        name="Tabby Franklin",
        email="tabby.franklin@hotmail.com",
    ),
    Customer(
        library_card_number="BD-952536-8456",
        name="Benoit Durant",
        email="benoit.durant@live.com",
    ),
    Customer(
        library_card_number="CW-033552-2361",
        name="Carla Weber",
        email="carla.weber@live.com",
    ),
    Customer(
        library_card_number="AL-194791-2763",
        name="Andras Lewerenz",
        email="andras.lewerenz@live.com",
    ),
    Customer(
        library_card_number="GA-366035-4809",
        name="Garwood Attridge",
        email="garwood.attridge@yahoo.com",
    ),
    Customer(
        library_card_number="HR-456360-6664",
        name="Helia Rivera",
        email="helia.rivera@outlook.com",
    ),
    Customer(
        library_card_number="GM-657559-1279",
        name="Garrett Mersh",
        email="garrett.mersh@yahoo.com",
    ),
    Customer(
        library_card_number="PB-727740-9390",
        name="Paige Bloomfield",
        email="paige.bloomfield@hotmail.com",
    ),
    Customer(
        library_card_number="VY-848083-4110",
        name="Vania Yates",
        email="vania.yates@hotmail.com",
    ),
    Customer(
        library_card_number="MS-978685-4081",
        name="Maddie Simons",
        email="maddie.simons@yahoo.com",
    ),
    Customer(
        library_card_number="RC-169069-5087",
        name="Ruth Craig",
        email="ruth.craig@gmail.com",
    ),
    Customer(
        library_card_number="MO-319428-1241",
        name="Monisola Ojo",
        email="monisola.ojo@live.com",
    ),
    Customer(
        library_card_number="EB-439675-6656",
        name="Eloise Beeson",
        email="eloise.beeson@yahoo.com",
    ),
    Customer(
        library_card_number="AS-480127-5576",
        name="Amala Sachs",
        email="amala.sachs@yahoo.com",
    ),
    Customer(
        library_card_number="MS-650635-7628",
        name="Monah Scarisbrick",
        email="monah.scarisbrick@live.com",
    ),
    Customer(
        library_card_number="YL-671948-9006",
        name="Yilma Loharani",
        email="yilma.loharani@live.com",
    ),
    Customer(
        library_card_number="AS-803202-7264",
        name="Alisha Srivastava",
        email="alisha.srivastava@outlook.com",
    ),
    Customer(
        library_card_number="EW-874254-5938",
        name="Eustace Wanell",
        email="eustace.wanell@hotmail.com",
    ),
    Customer(
        library_card_number="CC-014600-4221",
        name="Camille Craighall",
        email="camille.craighall@yahoo.com",
    ),
    Customer(
        library_card_number="LS-165215-5765",
        name="Lei Shirong",
        email="lei.shirong@yahoo.com",
    ),
    Customer(
        library_card_number="RI-315665-1111",
        name="Ryo Igarashi",
        email="ryo.igarashi@outlook.com",
    ),
    Customer(
        library_card_number="SP-407013-3259",
        name="Sunita Patel",
        email="sunita.patel@outlook.com",
    ),
    Customer(
        library_card_number="GN-497268-2337",
        name="Gareth Newton",
        email="gareth.newton@gmail.com",
    ),
    Customer(
        library_card_number="JT-638189-3786",
        name="Junpei Takayama",
        email="junpei.takayama@yahoo.com",
    ),
    Customer(
        library_card_number="DL-788806-8157",
        name="Devonne Luckhurst",
        email="devonne.luckhurst@live.com",
    ),
    Customer(
        library_card_number="RJ-989197-3123",
        name="Rebecca Joron",
        email="rebecca.joron@yahoo.com",
    ),
    Customer(
        library_card_number="VC-159532-1931",
        name="Veda Cartledge",
        email="veda.cartledge@outlook.com",
    ),
    Customer(
        library_card_number="SG-209799-9386",
        name="Sumit Ghosh",
        email="sumit.ghosh@gmail.com",
    ),
    Customer(
        library_card_number="FV-380771-3264",
        name="Fabien Vials",
        email="fabien.vials@yahoo.com",
    ),
    Customer(
        library_card_number="BJ-481163-3203",
        name="Brana Josefs",
        email="brana.josefs@outlook.com",
    ),
    Customer(
        library_card_number="RP-641879-6425",
        name="Rubin Petroff",
        email="rubin.petroff@live.com",
    ),
    Customer(
        library_card_number="AS-842374-2889",
        name="Artan Sayyid",
        email="artan.sayyid@outlook.com",
    ),
    Customer(
        library_card_number="NF-863210-2619",
        name="Ned Farmer",
        email="ned.farmer@live.com",
    ),
    Customer(
        library_card_number="JW-953809-8419",
        name="Jackson Wilkinson",
        email="jackson.wilkinson@yahoo.com",
    ),
    Customer(
        library_card_number="JH-104904-1738",
        name="Jade Harding",
        email="jade.harding@yahoo.com",
    ),
    Customer(
        library_card_number="PM-255343-6780",
        name="Pan Mirae",
        email="pan.mirae@hotmail.com",
    ),
    Customer(
        library_card_number="TE-435654-4935",
        name="Thomas Edwards",
        email="thomas.edwards@live.com",
    ),
    Customer(
        library_card_number="EB-535950-8147",
        name="Eveline Blanchar",
        email="eveline.blanchar@yahoo.com",
    ),
    Customer(
        library_card_number="MB-557137-7975",
        name="Maryann Bresner",
        email="maryann.bresner@yahoo.com",
    ),
    Customer(
        library_card_number="OI-617479-8470",
        name="Olufemi Ikande",
        email="olufemi.ikande@outlook.com",
    ),
    Customer(
        library_card_number="CC-708194-4538",
        name="Christelle Charron",
        email="christelle.charron@yahoo.com",
    ),
    Customer(
        library_card_number="ES-778817-3268",
        name="Eba Strand",
        email="eba.strand@yahoo.com",
    ),
    Customer(
        library_card_number="DB-899352-1003",
        name="Daphne Bishop",
        email="daphne.bishop@outlook.com",
    ),
    Customer(
        library_card_number="DC-969906-1592",
        name="Dalton Cleft",
        email="dalton.cleft@hotmail.com",
    ),
    Customer(
        library_card_number="TJ-151752-5225",
        name="Tan Jia",
        email="tan.jia@hotmail.com",
    ),
    Customer(
        library_card_number="MC-182037-2206",
        name="Macey Christie",
        email="macey.christie@outlook.com",
    ),
    Customer(
        library_card_number="VS-312469-3102",
        name="Valini Srinivas",
        email="valini.srinivas@live.com",
    ),
    Customer(
        library_card_number="SP-462994-5762",
        name="Stefa Padrick",
        email="stefa.padrick@outlook.com",
    ),
]

loans = [
    Loan(
        book_id=10,
        customer_library_card_number="TE-435654-4935",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=1,
        customer_library_card_number="TJ-151752-5225",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=11,
        customer_library_card_number="MB-557137-7975",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=19,
        customer_library_card_number="VS-312469-3102",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=50,
        customer_library_card_number="PM-255343-6780",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=49,
        customer_library_card_number="TE-435654-4935",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=32,
        customer_library_card_number="EB-535950-8147",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=26,
        customer_library_card_number="DB-899352-1003",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=20,
        customer_library_card_number="VC-159532-1931",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=17,
        customer_library_card_number="VS-312469-3102",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=35,
        customer_library_card_number="VS-312469-3102",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=3,
        customer_library_card_number="DL-788806-8157",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=46,
        customer_library_card_number="DL-788806-8157",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=33,
        customer_library_card_number="CC-708194-4538",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=31,
        customer_library_card_number="CC-014600-4221",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=30,
        customer_library_card_number="BJ-481163-3203",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=40,
        customer_library_card_number="AS-803202-7264",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=29,
        customer_library_card_number="OI-617479-8470",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=42,
        customer_library_card_number="MC-182037-2206",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=4,
        customer_library_card_number="TJ-151752-5225",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=45,
        customer_library_card_number="GM-657559-1279",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=5,
        customer_library_card_number="SG-209799-9386",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=43,
        customer_library_card_number="MS-650635-7628",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=7,
        customer_library_card_number="BJ-481163-3203",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=28,
        customer_library_card_number="GN-497268-2337",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=16,
        customer_library_card_number="SP-407013-3259",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=6,
        customer_library_card_number="PD-569797-8874",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=13,
        customer_library_card_number="RJ-989197-3123",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=23,
        customer_library_card_number="RC-169069-5087",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=15,
        customer_library_card_number="JW-953809-8419",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=36,
        customer_library_card_number="GN-497268-2337",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=34,
        customer_library_card_number="AS-842374-2889",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=22,
        customer_library_card_number="PB-727740-9390",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=2,
        customer_library_card_number="JT-638189-3786",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=8,
        customer_library_card_number="TE-435654-4935",
        date_loaned=date.today() - timedelta(days=randint(21, 42)),
        date_due=date.today() + timedelta(days=randint(-3, 18)),
        date_returned=None,
    ),
    Loan(
        book_id=8,
        customer_library_card_number="EB-439675-6656",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=43,
        customer_library_card_number="EW-874254-5938",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=44,
        customer_library_card_number="VS-312469-3102",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=11,
        customer_library_card_number="AL-194791-2763",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=27,
        customer_library_card_number="VY-848083-4110",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=17,
        customer_library_card_number="BJ-481163-3203",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=6,
        customer_library_card_number="PD-569797-8874",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=36,
        customer_library_card_number="DL-788806-8157",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=40,
        customer_library_card_number="TE-435654-4935",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=34,
        customer_library_card_number="TJ-151752-5225",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=19,
        customer_library_card_number="CW-033552-2361",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=24,
        customer_library_card_number="JT-638189-3786",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=26,
        customer_library_card_number="PD-569797-8874",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=23,
        customer_library_card_number="EB-535950-8147",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=7,
        customer_library_card_number="EW-874254-5938",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=20,
        customer_library_card_number="TJ-151752-5225",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=38,
        customer_library_card_number="FV-380771-3264",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=45,
        customer_library_card_number="HR-456360-6664",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=2,
        customer_library_card_number="TF-781410-1836",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=12,
        customer_library_card_number="CC-708194-4538",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=39,
        customer_library_card_number="TE-435654-4935",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=49,
        customer_library_card_number="SP-462994-5762",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=15,
        customer_library_card_number="SP-462994-5762",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=47,
        customer_library_card_number="RI-315665-1111",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=22,
        customer_library_card_number="CC-014600-4221",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=3,
        customer_library_card_number="AS-803202-7264",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=33,
        customer_library_card_number="SP-407013-3259",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=35,
        customer_library_card_number="BJ-481163-3203",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=21,
        customer_library_card_number="RP-641879-6425",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=9,
        customer_library_card_number="DC-969906-1592",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=37,
        customer_library_card_number="EB-439675-6656",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=48,
        customer_library_card_number="RJ-989197-3123",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=14,
        customer_library_card_number="ES-778817-3268",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=10,
        customer_library_card_number="HR-456360-6664",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=16,
        customer_library_card_number="VS-312469-3102",
        date_loaned=date.today() - timedelta(days=randint(42, 63)),
        date_due=date.today() - timedelta(days=randint(18, 39)),
        date_returned=date.today() - timedelta(days=randint(21, 42)),
    ),
    Loan(
        book_id=14,
        customer_library_card_number="BD-952536-8456",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=50,
        customer_library_card_number="PD-569797-8874",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=25,
        customer_library_card_number="CC-708194-4538",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=37,
        customer_library_card_number="CC-014600-4221",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=4,
        customer_library_card_number="SP-462994-5762",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=31,
        customer_library_card_number="MC-182037-2206",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=48,
        customer_library_card_number="AS-803202-7264",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=40,
        customer_library_card_number="JT-638189-3786",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=35,
        customer_library_card_number="GM-657559-1279",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=49,
        customer_library_card_number="PM-255343-6780",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=28,
        customer_library_card_number="PM-255343-6780",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=44,
        customer_library_card_number="MO-319428-1241",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=13,
        customer_library_card_number="GA-366035-4809",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=46,
        customer_library_card_number="MC-182037-2206",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=34,
        customer_library_card_number="DL-788806-8157",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=36,
        customer_library_card_number="MS-978685-4081",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=1,
        customer_library_card_number="DB-899352-1003",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=17,
        customer_library_card_number="FV-380771-3264",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=10,
        customer_library_card_number="DL-788806-8157",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=45,
        customer_library_card_number="CC-014600-4221",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=2,
        customer_library_card_number="PD-569797-8874",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=20,
        customer_library_card_number="EB-439675-6656",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=21,
        customer_library_card_number="MJ-600731-1698",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=19,
        customer_library_card_number="TJ-151752-5225",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=5,
        customer_library_card_number="MC-182037-2206",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=8,
        customer_library_card_number="MS-650635-7628",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=38,
        customer_library_card_number="BJ-481163-3203",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=6,
        customer_library_card_number="MS-650635-7628",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=41,
        customer_library_card_number="SP-407013-3259",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=3,
        customer_library_card_number="TJ-151752-5225",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=11,
        customer_library_card_number="PM-255343-6780",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=16,
        customer_library_card_number="SP-407013-3259",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=30,
        customer_library_card_number="AS-803202-7264",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=24,
        customer_library_card_number="MC-182037-2206",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=9,
        customer_library_card_number="BD-952536-8456",
        date_loaned=date.today() - timedelta(days=randint(63, 84)),
        date_due=date.today() - timedelta(days=randint(39, 60)),
        date_returned=date.today() - timedelta(days=randint(42, 63)),
    ),
    Loan(
        book_id=30,
        customer_library_card_number="RI-315665-1111",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=37,
        customer_library_card_number="EB-535950-8147",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=4,
        customer_library_card_number="YL-671948-9006",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=2,
        customer_library_card_number="DL-788806-8157",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=28,
        customer_library_card_number="EB-439675-6656",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=38,
        customer_library_card_number="SG-209799-9386",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=16,
        customer_library_card_number="HR-456360-6664",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=29,
        customer_library_card_number="FV-380771-3264",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=25,
        customer_library_card_number="FV-380771-3264",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=17,
        customer_library_card_number="NF-863210-2619",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=21,
        customer_library_card_number="VY-848083-4110",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=7,
        customer_library_card_number="MC-182037-2206",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=19,
        customer_library_card_number="ES-778817-3268",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=15,
        customer_library_card_number="CC-708194-4538",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=13,
        customer_library_card_number="TE-435654-4935",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=44,
        customer_library_card_number="DB-899352-1003",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=18,
        customer_library_card_number="TE-435654-4935",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=32,
        customer_library_card_number="JH-104904-1738",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=27,
        customer_library_card_number="DL-788806-8157",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=14,
        customer_library_card_number="OI-617479-8470",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=34,
        customer_library_card_number="AS-842374-2889",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=1,
        customer_library_card_number="SP-407013-3259",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=20,
        customer_library_card_number="JW-953809-8419",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=46,
        customer_library_card_number="AS-480127-5576",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=11,
        customer_library_card_number="RC-169069-5087",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=50,
        customer_library_card_number="MS-978685-4081",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=10,
        customer_library_card_number="AS-480127-5576",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=31,
        customer_library_card_number="JT-638189-3786",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=23,
        customer_library_card_number="TJ-151752-5225",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=5,
        customer_library_card_number="EB-535950-8147",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=26,
        customer_library_card_number="RI-315665-1111",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=36,
        customer_library_card_number="RC-169069-5087",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=45,
        customer_library_card_number="DB-899352-1003",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=35,
        customer_library_card_number="EB-535950-8147",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=41,
        customer_library_card_number="AS-842374-2889",
        date_loaned=date.today() - timedelta(days=randint(84, 105)),
        date_due=date.today() - timedelta(days=randint(60, 81)),
        date_returned=date.today() - timedelta(days=randint(63, 84)),
    ),
    Loan(
        book_id=19,
        customer_library_card_number="DC-969906-1592",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=8,
        customer_library_card_number="RJ-989197-3123",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=47,
        customer_library_card_number="EB-439675-6656",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=28,
        customer_library_card_number="VC-159532-1931",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=18,
        customer_library_card_number="CC-014600-4221",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=16,
        customer_library_card_number="DC-969906-1592",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=11,
        customer_library_card_number="PD-569797-8874",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=43,
        customer_library_card_number="PB-727740-9390",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=1,
        customer_library_card_number="MO-319428-1241",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=14,
        customer_library_card_number="BJ-481163-3203",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=32,
        customer_library_card_number="TF-781410-1836",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=46,
        customer_library_card_number="MB-557137-7975",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=13,
        customer_library_card_number="DC-969906-1592",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=30,
        customer_library_card_number="GA-366035-4809",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=10,
        customer_library_card_number="BJ-481163-3203",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=34,
        customer_library_card_number="MJ-600731-1698",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=4,
        customer_library_card_number="JH-104904-1738",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=23,
        customer_library_card_number="AL-194791-2763",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=49,
        customer_library_card_number="VY-848083-4110",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=15,
        customer_library_card_number="MJ-600731-1698",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=20,
        customer_library_card_number="RJ-989197-3123",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=29,
        customer_library_card_number="RI-315665-1111",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=41,
        customer_library_card_number="TF-781410-1836",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=3,
        customer_library_card_number="YL-671948-9006",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=5,
        customer_library_card_number="FV-380771-3264",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=27,
        customer_library_card_number="GN-497268-2337",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=6,
        customer_library_card_number="MC-182037-2206",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=33,
        customer_library_card_number="TE-435654-4935",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=36,
        customer_library_card_number="GN-497268-2337",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=17,
        customer_library_card_number="LS-165215-5765",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=26,
        customer_library_card_number="LS-165215-5765",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=7,
        customer_library_card_number="DC-969906-1592",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=48,
        customer_library_card_number="TF-781410-1836",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=35,
        customer_library_card_number="HR-456360-6664",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
    Loan(
        book_id=21,
        customer_library_card_number="MS-650635-7628",
        date_loaned=date.today() - timedelta(days=randint(105, 126)),
        date_due=date.today() - timedelta(days=randint(81, 102)),
        date_returned=date.today() - timedelta(days=randint(84, 105)),
    ),
]
